### ISSUE TITLE
The locale is reset when the date of the picker is set from code

### ISSUE THREAD

**Issue by RenanITAO** [Eonasdan/tempus-dominus#2430]
When the `locale` is set in the `options` object, everything works well, until the date is set by code. At this moment, the `locale` switches back to `default`. The issue is the same if the `defaultDate` is set in the `options` object. Example in [this StackBlitz](https://stackblitz.com/edit/tempus-dominus-v6-simple-setup-ycwbii?file=index.js).

As you can see in the commented line in the StackBlitz, a workaround is to set the `locale` of the `DateTime` object passed to the `dates.set` method.

Many thanks for your work

**Comment by Eonasdan** [comment]
Hello. Please check your issue with this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next?file=index.html). I believe I've fixed this in the `development` branch, which I'll publish soon.
Please note that jsdelivr is a CDN and might have a cached copy.

**Comment by RenanITAO** [comment]
Hello,

Sorry, I still have the issue. Please have a look at this [stackblitz](https://stackblitz.com/edit/tempus-dominus-v6-next-kkxytv?file=index.js). The `defaultDate` is set and the locale is reset to `default`.

**Comment by Eonasdan** [comment]
@RenanITAO hi, I think I fixed this for real this time. It's in the development branch. The stackblitz might take some time for the cnd to catch up

**Comment by William-H-M** [comment]
Confirm fixed with local copy of dev-branch

![imagen](https://user-images.githubusercontent.com/24443241/146425484-32289369-2289-4537-bd1a-673ad00792d7.png)

**Comment by jcompagner** [comment]
i think this causes a regression:

    if (eData?.tdTargetInput) delete eData.tdTargetInput;
    if (eData?.tdTargetToggle) delete eData.tdTargetToggle;

so from the data dom list those 2 are deleted (in options.ts when merging and looking at the dom.dataset)

but then when we initialize the toggle:

  private _initializeToggle() {
    if (this._options.display.inline) return;
    let query = this._element.dataset.tdTargetToggle;

we expect that that value is there..
But it isn't anymore it was just deleted..

you can also see this in the default example:

https://getdatepicker.com/6/examples/no-styles.html

clicking in the input will cause the popup to be there (and by default that shouldn;t happen that show on input is default false)
