### ISSUE TITLE
useTwentyfourHour hour-range is 01 - 24, should be 00 - 23

### ISSUE THREAD

**Issue by drsnok** [Eonasdan/tempus-dominus#2600]
- Operating: Windows 10
- Browser: Chrome 103.0.5060.66, Edge 103.0.1264.44
- Version of the plugin. 6.0.0-beta9.
- Stackblitz fork: [https://stackblitz.com/edit/tempus-dominus-v6-next-ajtgmm?file=index.js](https://stackblitz.com/edit/tempus-dominus-v6-next-ajtgmm?file=index.js)
 - Browser's locale: sv-SE

When using the useTwentyfourHour-setting the hour-range is between 01 - 24, should be 00 - 23.
[Maybe related to this ticket?](https://github.com/Eonasdan/tempus-dominus/issues/2548)

**Comment by Eonasdan** [comment]
This is fixed in beta9

**Comment by confuzeus** [comment]
The issue is still here in beta9.

Without specifying a locale, clock is 1-24.
![Screenshot from 2022-07-27 00-50-19](https://user-images.githubusercontent.com/22542909/181109435-4f257134-bb7d-4c36-9125-6a04afb3f2ef.png)

**Comment by chrischu** [comment]
This bug definitely still exists in 6.2.4, even when specifying a locale.

This can even be reproduced on https://getdatepicker.com/6/plugins/customDateFormat.html by
* setting the locale to "default"
* clicking change
* the display now uses 1-24 instead of 0-23

Afterwards changing the locale back does NOT fix the issue, so I'm thinking there bug happens only when changing the locale for the first time or something.

**Comment by confuzeus** [comment]
I switched to [flatpicker](https://github.com/flatpickr/flatpickr) because I couldn't figure out to solve this issue.

**Comment by Eonasdan** [comment]
As I mentioned somewhere else, there doesn't seem to be a consensus on what is

**Comment by chrischu** [comment]
But is apparently also locale-dependend (when using en-GB instead of en-US it returns `00`).

**Comment by chrischu** [comment]
Found some new information: apparently `hour12: false` overrides `hourCycle: 'h23'`, so what does work in both Firefox/Chrome is `Intl.DateTimeFormat('en', { hour: '2-digit', hourCycle: 'h23' }).formatToParts(new Date(2000, 1, 1, 0, 0, 0))[0].value`.

**Comment by Eonasdan** [comment]
I had a note to look at [`Intl.Locale()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/Locale). This seems to report h12, h23, h24 depending on the locale. I'll see if I can use this to decide what the range of the hour should be.

**Comment by Eonasdan** [comment]
Hey everyone, please check out this [StackBlitz.](https://stackblitz.com/edit/tempus-dominus-v2600-usetwentyfourhour?file=index.js). I added some code that tried to guess the `hourCycle`. Please try your locales and let me know if it doesn't work.

**Comment by Eonasdan** [comment]
This has been merged into dev.

**Comment by amorebietakoUdala** [comment]
Hi,

If you initiliaze date with 00:00 time, it changes to 24:00. When yo click the clock button it display 00:00 but it show 24:00 in the field. Here is the example:

https://tempus-dominus-v6-simple-setup-import-7wv6ta.stackblitz.io

Seems to work well in v6.0.0-beta9. So it's broken somewhere between beta9 and 6.2.8.

**Comment by Eonasdan** [comment]
@amorebietakoUdala please try 6.2.10. Sorry about that.

**Comment by amorebietakoUdala** [comment]
I'll do. Thank you very much to you for sharing this awesome datetime picker.
